packages:
  '@twin-digital/eslint-config':
    rules:
      eslint: false
      eslint-config-bootstrap: false
  '@twin-digital/opus-scripts':
    rules:
      eslint: false
      eslint-config-bootstrap: false
      typescript: false
      typescript-dependencies: false
      typescript-scripts-and-dependencies: false
      typescript-with-options: false
  '@twin-digital/tsconfig':
    rules:
      eslint: false
      eslint-config-bootstrap: false
      typescript: false
      typescript-dependencies: false
      typescript-scripts-and-dependencies: false
      typescript-with-options: false

features:
  - name: eslint
    actions:
      - action: write-file
        options:
          file: eslint.config.js
          content: |
            import base from '@twin-digital/eslint-config'

            export default base

      - action: json-merge-patch
        options:
          file: package.json
          patch: |
            scripts:
              lint: lint
              'lint:fix': lint_fix
            devDependencies:
              '@eslint/js': 'catalog:'
              '@twin-digital/eslint-config': workspace:*
              '@twin-digital/opus-scripts': workspace:*
              eslint: 'catalog:'
              eslint-config-prettier: 'catalog:'
              globals: 'catalog:'
              prettier: 'catalog:'
              prettier-package-json: 'catalog:'
              typescript-eslint: 'catalog:'
  - name: package-manifest
    actions:
      # if project has source files...
      - name: Add files entries
        action: json-patch
        conditions:
          - exists: src/*
        options:
          file: package.json
          patch: |
            - opx: appendIfMissing
              path: /files
              value: dist
            - opx: appendIfMissing
              path: /files
              value: "!dist/**/*.d.ts.map"
      - name: Add esm exports
        action: json-merge-patch
        conditions:
          - exists: src/**/index.ts
        options:
          file: package.json
          patch: |
            exports:
              .:
                import:
                  types: ./dist/index.d.ts
                  import: ./dist/index.js
              ./*:
                import:
                  types: ./dist/*/index.d.ts
                  import: ./dist/*/index.js
      - name: Add cjs exports
        action: json-merge-patch
        conditions:
          - exists: tsconfig.cjs.json
        options:
          file: package.json
          patch: |
            exports:
              .:
                require:
                  types: ./dist/cjs/index.d.ts
                  require: ./dist/cjs/index.js
              ./*:
                require:
                  types: ./dist/cjs/*/index.d.ts
                  require: ./dist/cjs/*/index.js
      - name: Remove unnecessary cjs exports
        action: json-merge-patch
        conditions:
          - notExists: tsconfig.cjs.json
        options:
          file: package.json
          patch: |
            exports:
              .:
                require: null
              ./*:
                require: null
      # if project does not have source files...
      - name: Remove files entries
        action: json-patch
        conditions:
          - notExists: src/*
        options:
          file: package.json
          patch: |
            - opx: removeValue
              path: /files
              value: dist
            - opx: removeValue
              path: /files
              value: '!dist/**/*.d.ts.map'
      - name: Remove exports
        action: json-merge-patch
        conditions:
          - notExists: src/**/index.ts
        options:
          file: package.json
          patch: |
            exports:
              .: null
              ./*: null
  - name: typescript
    actions:
      - name: Create tsconfig file
        action: write-file
        conditions:
          - notExists: tsconfig.options.json
        options:
          file: tsconfig.json
          content: |
            {
              "extends": ["@twin-digital/tsconfig/tsconfig.build.json"]
            }
      - name: Create tsconfig file with custom options
        action: write-file
        conditions:
          - exists: tsconfig.options.json
        options:
          file: tsconfig.json
          content: |
            {
              "extends": [
                "@twin-digital/tsconfig/tsconfig.build.json",
                "./tsconfig.options.json"
              ]
            }
      - name: Add scripts and dependencies
        action: json-merge-patch
        options:
          file: package.json
          patch: |
            scripts:
              build: build
              typecheck: tsc --noEmit
              watch: watch
            devDependencies:
              '@twin-digital/opus-scripts': workspace:*
              '@types/node': '22.x'
              typescript: 'catalog:'
  - name: clean
    actions:
      - name: Add script
        action: json-merge-patch
        options:
          file: package.json
          patch: |
            scripts:
              clean: clean
