services:
  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:8080'
    environment:
      - NODE_ENV=development
    develop:
      watch:
        # Sync compiled dist files and restart the Lambda container
        - action: sync+restart
          path: ./dist
          target: /var/task/dist
        # If package.json changes, rebuild container
        - action: rebuild
          path: ./package.json
