services:
  web-server:
    build:
      context: .
      dockerfile: web-server/Dockerfile
    ports:
      - '8080:80'
    develop:
      watch:
        # Sync .bookify/dist to /srv/www
        - path: ./.bookify/dist
          action: sync
          target: /srv/www
    restart: unless-stopped
